//
//  MainListModels.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


enum BoardType {
    static let data = "data"
    static let todo = "todo"
}

enum MainList {
    
    // MARK: - User models
    
    enum ShowUser {
        struct Request {
            
        }
        struct Response {
            var user: User?
        }
        struct ViewModel {
            var username: String
            var imageData: Data?
        }
    }
    enum ChangeUserName {
        
        struct Request {
            var userName: String
        }
        struct Response {
            var user: User?
        }
        struct ViewModel {
            var userName: String
        }
    }
    enum ChangePassword {
        
        struct Request {
            var oldPassword: String
            var newPassword: String
            var confirmPassword: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    enum ChangeUserImage {
        struct Request {
            var imageData: Data
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    // MARK:  - Boards models
   
    enum GetBoard {
        struct Request {
            var indexPath: IndexPath
        }
        struct Response {
            var indexPath: IndexPath
            var name: String
            var type: String
            var status: Bool
        }
    }
    
    enum ShowBoards {
        struct Request {
            
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum CreateNewBoard {
        struct Request {
            var name: String
            var type: String
        }
        struct Response {
            var board: Board
        }
        struct ViewModel {
            var name: String
            var type: String
        }
    }
    
    enum EditBoardName {
        struct Request {
            var name: String
            var indexPath: IndexPath
        }
        struct Response {
            var name: String
            var indexPath: IndexPath
        }
        struct ViewModel {
            var name: String
            var indexPath: IndexPath
        }
    }
    enum DeleteBoard {
        struct Request {
            var indexPath: IndexPath
        }
        struct Response {
            var indexPath: IndexPath
        }
        struct ViewModel {
            var indexPath: IndexPath
        }
    }
    enum DisplayMessage {
        struct Request {
            
        }
        struct Response {
            var title: String
            var message: String
        }
        struct ViewModel {
            var title: String
            var message: String
            var buttonTitle: String
        }
    }
    
}
