//
//  MainListPresenter.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainListPresentationLogic {
    func presentUser(response: MainList.ShowUser.Response)
    func presentBoards(response: MainList.ShowBoards.Response)
    func presentNewBoard(response: MainList.CreateNewBoard.Response)
    func presentChangedBoard(response: MainList.EditBoardName.Response)
    func deleteBoard(response: MainList.DeleteBoard.Response)
    
    func presentError(response: MainList.DisplayMessage.Response)
}

class MainListPresenter: MainListPresentationLogic {

    

    
    weak var viewController: MainListDisplayLogic?
    
    // MARK: Presentation logic
    
    func presentUser(response: MainList.ShowUser.Response) {
        
        let viewModel = MainList.ShowUser.ViewModel(username: response.user?.name ?? "Error", imageData: response.user?.imageData)
        viewController?.displayUser(viewModel: viewModel)
    }
    
    func presentBoards(response: MainList.ShowBoards.Response) {
        let viewModel = MainList.ShowBoards.ViewModel(boardsNames: response.boardsNames)
        viewController?.displayBoards(viewModel: viewModel)
    }
    
    func presentNewBoard(response: MainList.CreateNewBoard.Response) {
        let viewModel = MainList.CreateNewBoard.ViewModel(name: response.name)
        viewController?.displayNewBoard(viewModel: viewModel)
    }
    
    func presentChangedBoard(response: MainList.EditBoardName.Response) {
        let viewModel = MainList.EditBoardName.ViewModel(name: response.name, indexPath: response.indexPath)
        viewController?.displayEditedBoard(viewModel: viewModel)
    }
    
    func deleteBoard(response: MainList.DeleteBoard.Response) {
        let viewModel = MainList.DeleteBoard.ViewModel(indexPath: response.indexPath)
        viewController?.deleteBoard(viewModel: viewModel)
    }
    
}

// MARK:  - Present Errors

extension MainListPresenter {
    func presentError(response: MainList.DisplayMessage.Response) {
        let viewModel = MainList.DisplayMessage.ViewModel(
            title: response.title,
            message: response.message,
            buttonTitle: "Ok")
        viewController?.displayMessage(viewModel: viewModel)
    }
}
