//
//  MainListInteractor.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainListBusinessLogic {
    func showUser(request: MainList.ShowUser.Request)
    func changeUserName(request: MainList.ChangeUserName.Request)
    func changePassword(request: MainList.ChangePassword.Request)
    func changeUserImage(request: MainList.ChangeUserImage.Request)
    
    func showBoards(request: MainList.ShowBoards.Request)
    func createNewBoard(request: MainList.CreateNewBoard.Request)
    func editBoardName(request: MainList.EditBoardName.Request)
    func deleteBoard(request: MainList.DeleteBoard.Request)
   

}

protocol MainListDataStore {
    var user: User! { get set }
    
    var boards: [Board] { get }
}

class MainListInteractor: MainListBusinessLogic, MainListDataStore {
    
    var user: User!
    var boards: [Board] = []

    
    //var name: String
    weak var viewController: MainListViewController?
    var presenter: MainListPresentationLogic?
    
    
    
    // MARK: Do something
    
    func showUser (request: MainList.ShowUser.Request) {
        let response = MainList.ShowUser.Response(user: user)
        presenter?.presentUser(response: response)
    }
    
    func showBoards (request: MainList.ShowBoards.Request) {
        boards = CoreDataManager.shared.getBoards(user: user)
        boards.sort { (board1, board2) -> Bool in
            board1.id < board2.id
        }
        
        var boardsNames: [String] = []
        boards.forEach { board in
            boardsNames.append(board.name ?? "Error")
        }
        
        let response = MainList.ShowBoards.Response(boardsNames: boardsNames)
        presenter?.presentBoards(response: response)
    }
    
    
    
    func createNewBoard(request: MainList.CreateNewBoard.Request) {
        //let board = CoreDataManager.shared.createBoard(userName: name, boardName: request.name)
        guard let board = CoreDataManager.shared.createBoard(user: user, boardName: request.name, id: boards.count) else {
            let response = MainList.DisplayMessage.Response(title: "Creating Failed", message: "Try Again")
            presenter?.presentError(response: response)
            return
        }
        boards.append(board)
        let response = MainList.CreateNewBoard.Response(name: board.name ?? "Error")
        presenter?.presentNewBoard(response: response)
        
    }
    
    func editBoardName(request: MainList.EditBoardName.Request) {
        let board = boards[request.indexPath.row]
        board.name = request.name
        if CoreDataManager.shared.saveChanges() {
            let response = MainList.EditBoardName.Response(name: board.name ?? "Error", indexPath: request.indexPath)
            presenter?.presentChangedBoard(response: response)
        }
        else {
            let response = MainList.DisplayMessage.Response(title: "Changing Failed", message: "Try Again")
            presenter?.presentError(response: response)
        }
    }
    
    func deleteBoard(request: MainList.DeleteBoard.Request) {
        if CoreDataManager.shared.deleteBoard(board: boards[request.indexPath.row]) {
            boards.remove(at: request.indexPath.row)
            renumberBoards()
            let response = MainList.DeleteBoard.Response(indexPath: request.indexPath)
            presenter?.deleteBoard(response: response)
        }
        else {
            let response = MainList.DisplayMessage.Response(title: "Error", message: "Deleting Failed")
            presenter?.presentError(response: response)
        }
    }
    //Used when delete board
    func renumberBoards() {
        for (index, board) in boards.enumerated() {
            board.id = Int64(index)
        }
    }
    
    
    // MARK:  - User Field Changing
    
    func changeUserName(request: MainList.ChangeUserName.Request) {
        user.name = request.userName
        if CoreDataManager.shared.saveChanges() {
            let response = MainList.ShowUser.Response(user: user)
            presenter?.presentUser(response: response)
        }
        else {
            let response = MainList.DisplayMessage.Response(title: "Changing Failed", message: "Try Again")
            presenter?.presentError(response: response)
        }
    }
    
    func changePassword(request: MainList.ChangePassword.Request){
        let oldPasswordHash = CoreDataManager.shared.encryptString(string: request.oldPassword)
        
        // Check old password
        guard oldPasswordHash == user.passwordHash else {
            let response = MainList.DisplayMessage.Response(title: "Password is incorrect", message: "Try Again")
            presenter?.presentError(response: response)
            return
        }
        
        // Check new passwords
        guard request.newPassword == request.confirmPassword else {
            let response = MainList.DisplayMessage.Response(title: "New passwords don't match", message: "Try Again")
            presenter?.presentError(response: response)
            return
        }
        
        // Changing password
        let newPasswordHash = CoreDataManager.shared.encryptString(string: request.newPassword)
        user.passwordHash = newPasswordHash
        if CoreDataManager.shared.saveChanges() {
            let response = MainList.DisplayMessage.Response(title: "Success", message: "Password was changed")
            presenter?.presentError(response: response)
        }
        else {
            let response = MainList.DisplayMessage.Response(title: "Changing failed", message: "Try Again")
            presenter?.presentError(response: response)
        }
        
    }
    
    func changeUserImage(request: MainList.ChangeUserImage.Request) {
        user.imageData = request.imageData
        if CoreDataManager.shared.saveChanges() {
            let response = MainList.ShowUser.Response(user: user)
            presenter?.presentUser(response: response)
        }
        else {
            let response = MainList.DisplayMessage.Response(title: "Changing Failed", message: "Try Again")
            presenter?.presentError(response: response)
        }
    }
    
}
