//
//  MainListRouter.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainListRoutingLogic {
    func navigateByIndexPath(indexPath: IndexPath)
}

protocol MainListDataPassing {
    var dataStore: MainListDataStore? { get }
}

class MainListRouter: NSObject, MainListRoutingLogic, MainListDataPassing {
    weak var viewController: MainListViewController?
    var dataStore: MainListDataStore?
    
    //MARK: Navigation
    
    func navigateByIndexPath(indexPath: IndexPath) {
        
        if indexPath.section == 0 {
            navigateToTaskList(indexPath: indexPath)
        } else {
            navigateToDeskBoard(indexPath: indexPath)
        }
      
    }
    
     // MARK:  - Navigate to TASK LIST
    
    private func navigateToTaskList(indexPath: IndexPath) {
        let taskListVC = TaskListViewController(nibName: nil, bundle: nil)
        let navigationController = UINavigationController(rootViewController: taskListVC)
        navigationController.modalPresentationStyle = .fullScreen
        
        var taskListDS = taskListVC.router!.dataStore!

        viewController!.present(navigationController, animated: true)
        passDataToTaskList(source: dataStore!, destination: &taskListDS, indexPath: indexPath)

    }
    
    func passDataToTaskList(source: MainListDataStore, destination: inout TaskListDataStore, indexPath: IndexPath) {
        let board = source.toDoBoards[indexPath.row]
        destination.board = board
    }
    
    
    // MARK:  - Navigate to Desk Board
    
    private func navigateToDeskBoard(indexPath: IndexPath) {
        let boardDeskVC = BoardDeskViewController(nibName: nil, bundle: nil)
        let navigationController = UINavigationController(rootViewController: boardDeskVC)
        navigationController.modalPresentationStyle = .fullScreen
        
        var boardDeskDS = boardDeskVC.router!.dataStore!
        
        viewController!.present(navigationController, animated: true)
        passDataToBoardDesk(source: dataStore!, destination: &boardDeskDS, indexPath: indexPath)
    }
    
    func passDataToBoardDesk(source: MainListDataStore, destination: inout BoardDeskDataStore, indexPath: IndexPath) {
        let board = source.dataBoards[indexPath.row]
        destination.board = board
    }
    
}
