//
//  MainListRouter.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainListRoutingLogic {
    func navigateToBoardDesk(indexPath: IndexPath)
}

protocol MainListDataPassing {
    var dataStore: MainListDataStore? { get }
}

class MainListRouter: NSObject, MainListRoutingLogic, MainListDataPassing {
    weak var viewController: MainListViewController?
    var dataStore: MainListDataStore?
    
    
    
    //MARK: Navigation
    
    func navigateToBoardDesk(indexPath: IndexPath) {
        let boardDeskVC = BoardDeskViewController(nibName: nil, bundle: nil)
        
        let navigationController = UINavigationController(rootViewController: boardDeskVC)
        navigationController.modalPresentationStyle = .fullScreen
        
        navigationController.modalPresentationStyle = .fullScreen
        
        var boardDeskDS = boardDeskVC.router!.dataStore!
        
        viewController!.present(navigationController, animated: true)
        passDataToBoardDesk(source: dataStore!, destination: &boardDeskDS, indexPath: indexPath)
    }
    
    // MARK: Passing data
    
    func passDataToBoardDesk(source: MainListDataStore, destination: inout BoardDeskDataStore, indexPath: IndexPath) {
        destination.board = source.boards[indexPath.row]
    }
}
