//
//  MainListModels.swift
//  SecureStore
//
//  Created by macSlm on 03.03.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainList {
    // MARK: Use cases
    
    enum ShowBoards {
        struct Request {
            
        }
        struct Response {
            var username: String
        }
        struct ViewModel {
            var username: String
        }
    }
}
