//
//  BoardDeskInteractor.swift
//  SecureStore
//
//  Created by macSlm on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BoardDeskBusinessLogic {
    func showBoard(request: BoardDesk.ShowBoard.Request)
    func getCountOfUnits() -> Int
    func getUnit(indexPath: IndexPath) -> (type: String, data: Data?, text: String?)
    
    func createImageUnit(request: BoardDesk.CreateUnit.Request)
    func createTextUnit(request: BoardDesk.CreateUnit.Request)
    func deleteUnit(request: BoardDesk.DeleteUnit.Request)
    
    func changeTextUnit(request: BoardDesk.ChangingTextUnit.Request) 
}

protocol BoardDeskDataStore {
    var board: Board! { get set }
    var units: [BoardUnit] { get }
}

class BoardDeskInteractor: BoardDeskBusinessLogic, BoardDeskDataStore {
    var presenter: BoardDeskPresentationLogic?
    var worker: BoardDeskWorker?
    
    var board: Board!
    var units: [BoardUnit] = []
    
    // MARK: Show the board
    
    func showBoard(request: BoardDesk.ShowBoard.Request) {
        units = CoreDataManager.shared.getUnits(board: board)
        units.sort { (unit1, unit2) -> Bool in
            unit1.id < unit2.id
        }
        
        let response = BoardDesk.ShowBoard.Response(board: board)
        presenter?.presentBoard(response: response)
    }
    
    // MARK:  - GETTING FROM DATASTORE
    
    func getCountOfUnits() -> Int {
 
        return units.count
    }
    
    func getUnit(indexPath: IndexPath) -> (type: String, data: Data?, text: String?) {
        let unit = units[indexPath.row]
        print (unit.type!)
        return (unit.type!, unit.data, unit.text)
    }
    
    // MARK:  - CREATING UNITS
    
    func createImageUnit(request: BoardDesk.CreateUnit.Request){
        guard let unit = CoreDataManager.shared.createImageUnit(board: board, unitType: UnitType.image, data: request.data, id: units.count) else {
            
            let response = BoardDesk.Message.Response(title: "Unit saving unsuccess", message: "Try again")
            presenter?.presentMessage(response: response)
            return
        }
        
        units.append(unit)
        presenter?.presentNewUnit()
        
    }
    
    func createTextUnit(request: BoardDesk.CreateUnit.Request) {
        guard let unit = CoreDataManager.shared.createTextUnit(board: board, unitType: UnitType.text, text: "", id: units.count) else {
            
            let response = BoardDesk.Message.Response(title: "Unit saving unsuccess", message: "Try again")
            presenter?.presentMessage(response: response)
            return
        }
        
        units.append(unit)
        presenter?.presentNewUnit()
    }
    
    // MARK:  - Edditing Units
    
    //Used when delete unit
    func renumberUnits() {
        for (index, unit) in units.enumerated() {
            unit.id = Int64(index)
        }
    }
    
    
    func deleteUnit(request: BoardDesk.DeleteUnit.Request) {
        print("Units count: \(units.count)")
        print("Index: \(request.indexPath.row)")
        
        if CoreDataManager.shared.deleteUnit(unit: units[request.indexPath.row]) {
            units.remove(at: request.indexPath.row)
            renumberUnits()
            let response = BoardDesk.DeleteUnit.Response(indexPath: request.indexPath)
            presenter?.deleteUnit(response: response)
        }
        else {
            let response = BoardDesk.Message.Response(title: "Error", message: "Deleting Failed")
            presenter?.presentMessage(response: response)
        }
    }
    
    func changeTextUnit(request: BoardDesk.ChangingTextUnit.Request) {
        let unit = units[request.indexPatch.row]
        unit.text = request.text
        if CoreDataManager.shared.saveChanges() {
            let response = BoardDesk.Message.Response(title: "Saving successful", message: "")
            presenter?.presentMessage(response: response)
        }
        else {
            let response = BoardDesk.Message.Response(title: "Saving Failed", message: "Try Again")
            presenter?.presentMessage(response: response)
        }
    }
    
}
