//
//  BoardDeskModels.swift
//  SecureStore
//
//  Created by macSlm on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UnitType {
    static let image = "image"
    static let text = "text"
    static let todo = "todo"
}

enum BoardDesk {

    enum ShowBoard {
        struct Request {
        }
        struct Response {
            var board: Board
        }
        struct ViewModel {
            var boardName: String
            var units: [BoardUnit]
        }
    }
    
    enum CreateUnit {
        struct Request {
            var data: Data
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    enum DeleteUnit {
        struct Request {
            var indexPath: IndexPath
        }
        struct Response {
            var indexPath: IndexPath
        }
        struct ViewModel {
            var indexPath: IndexPath
        }
    }
    
    
    enum Message {
        struct Request {
            
        }
        struct Response {
            var title: String
            var message: String
        }
        struct ViewModel {
            var title: String
            var message: String
            var buttonTitle: String
        }
    }
    
    enum ChangingTextUnit {
        struct Request {
            var indexPatch: IndexPath
            var text: String
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
    
    
    
}
