//
//  BoardDeskPresenter.swift
//  SecureStore
//
//  Created by macSlm on 24.04.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BoardDeskPresentationLogic {
    
    func presentMessage(response: BoardDesk.Message.Response)
    
    func presentBoard(response: BoardDesk.ShowBoard.Response)
    func presentNewUnit()
    func deleteUnit(response: BoardDesk.DeleteUnit.Response)
}

class BoardDeskPresenter: BoardDeskPresentationLogic {
    weak var viewController: BoardDeskDisplayLogic?
    
    // MARK: Do something
    
    func presentBoard(response: BoardDesk.ShowBoard.Response) {
        let viewModel = BoardDesk.ShowBoard.ViewModel(boardName: response.board.name!, units: [])
        viewController?.displayBoard(viewModel: viewModel)
    }
    
    func presentNewUnit() {
        
        viewController?.displayNewUnit()
    }
    
    func deleteUnit(response: BoardDesk.DeleteUnit.Response) {
        let viewModel = BoardDesk.DeleteUnit.ViewModel(indexPath: response.indexPath)
        viewController?.deleteUnit(viewModel: viewModel)
    }
    
    
    
    func presentMessage(response: BoardDesk.Message.Response) {
        let viewModel = BoardDesk.Message.ViewModel(
            title: response.title,
            message: response.message,
            buttonTitle: "Ok")
        viewController?.displayMessageAlert(viewModel: viewModel)
    }
    
}
