//
//  TaskListPresenter.swift
//  SecureStore
//
//  Created by macSlm on 03.06.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskListPresentationLogic {
    func presentBoard(response: TaskList.ShowBoard.Response)
    
    func presentNewTask(response: TaskList.CreateTask.Response)
    func presentChangedTask(response: TaskList.EditTaskName.Response)
    func deleteTask(response: TaskList.DeleteTask.Response)
    
    func presentMessage(response: TaskList.DisplayMessage.Response)
    
}

class TaskListPresenter: TaskListPresentationLogic {
    
    weak var viewController: TaskListDisplayLogic?
    
    // MARK: - BOARD
    
    func presentBoard(response: TaskList.ShowBoard.Response) {
        let viewModel = TaskList.ShowBoard.ViewModel(boardName: response.board.name ?? "Error".localized())
        viewController?.displayBoard(viewModel: viewModel)
    }
    
    // MARK:  - TASKS
    func presentNewTask(response: TaskList.CreateTask.Response) {
        let viewModel = TaskList.CreateTask.ViewModel(taskName: response.task.name ?? "Error".localized())
        viewController?.displayNewTask(viewModel: viewModel)
    }
    
    func presentChangedTask(response: TaskList.EditTaskName.Response) {
        let viewModel = TaskList.EditTaskName.ViewModel(name: response.task.name ?? "Error", indexPath: response.indexPath)
        viewController?.displayEditedTask(viewModel: viewModel)
    }
    
    func deleteTask(response: TaskList.DeleteTask.Response) {
        viewController?.deleteTask(viewModel: TaskList.DeleteTask.ViewModel(indexPath: response.indexPath))
    }
    
    // MARK:  - ERROR PROCESSING
    func presentMessage(response: TaskList.DisplayMessage.Response) {
        let viewModel = TaskList.DisplayMessage.ViewModel(
            title: response.title,
            message: response.message,
            buttonTitle: "Ok")
        viewController?.displayMessage(viewModel: viewModel)
    }
}
