//
//  LoginRouter.swift
//  SecureStore
//
//  Created by macSlm on 16.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func navigateToMainList()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    
    
    
    
    weak var viewController: LoginViewController!
    var dataStore: LoginDataStore?
    
    // MARK: Navigation
    
    func navigateToMainList() {
        
        let mainListVC = MainListViewController(nibName: nil, bundle: nil)
        let navigationController = UINavigationController(rootViewController: mainListVC)
        navigationController.modalPresentationStyle = .fullScreen
        
        var mainListDS = mainListVC.router!.dataStore!
        
        viewController.present(navigationController, animated: true)
        passDataToMainList(source: dataStore!, destination: &mainListDS)
        
    
    }
    
    // MARK: Passing data
    
    func passDataToMainList(source: LoginDataStore, destination: inout MainListDataStore) {
        destination.user = source.user
    }
}
