//
//  LoginPresenter.swift
//  SecureStore
//
//  Created by macSlm on 16.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
    func login(response: Login.Login.Response)
    func signUp(response: Login.SignUp.Response)
    func showAlert(response: Login.ShowAlert.Response)
    func getLanguage()
    func moveToMainlist()
}

class LoginPresenter: LoginPresentationLogic {
   
    func showAlert(response: Login.ShowAlert.Response) {
        let title = ""
        let message = response.errorMessage
        let buttonTitle = "Ok"
        
        let viewModel = Login.ShowAlert.ViewModel(title: title, message: message, buttonTitle: buttonTitle)
        viewController?.clearTextFields()
        viewController?.showAlert(viewModel: viewModel)
        
    }
    

    weak var viewController: LoginDisplayLogic?
  
    // MARK: Do something
  
    func login(response: Login.Login.Response) {
        let viewModel = Login.Login.ViewModel()
        viewController?.displayLogin(viewModel: viewModel)
        viewController?.clearTextFields()
    }
    
    func signUp(response: Login.SignUp.Response) {
        
       // let viewModel = Login.SignUp.ViewModel()
        
        
    }
    
    func getLanguage() {
        let viewModel = Login.Texts.ViewModel(textList: TextList.shared.getloginUI())
        viewController?.setupUI(viewModel: viewModel)

    }
    func moveToMainlist() {
        viewController?.moveToMainList()
    }
    
    
}
