//
//  LoginWorker.swift
//  SecureStore
//
//  Created by macSlm on 16.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

// MARK: - TEXT FIELDS CHECKING

class LoginWorker {
    
    func check3Fields(userName: String?, password: String?, confirmPassword: String?) -> String {
        //let textList = TextList.shared.getloginUI()
        var message = "Success".localized()
        //
        
        guard let userName = userName, let password = password, let confirmPassword = confirmPassword  else {
            message = "Some fields are empty".localized()
            return message
        }
        if password != confirmPassword {
            message = "Passwords do not match".localized()
        }
        

        
        if userName == "" || password == "" || confirmPassword == "" {
            message = "Some fields are empty".localized()
        }
        
        for symbol in userName {
            if symbol == " " {
                message = "Username cannot contain a space".localized()
            }
        }
        
        return message
    }
}

// MARK: - USER DEFAULTS

extension LoginWorker {
    
    func compareUsers(userName: String, passwordHash: String) -> User? {
        
        let users = CoreDataManager.shared.fetchUsers()
        for user in users {
            if user.name == userName && user.passwordHash == passwordHash {
                return user
            }
        }
        return nil
    }
    
    func checkUserInStore(userName: String) -> Bool {
        var success = true
        let users = CoreDataManager.shared.fetchUsers()
        for user in users {
            if user.name == userName  {
                success = false
            }
        }
        return success
    }
    
}





