//
//  LoginWorker.swift
//  SecureStore
//
//  Created by macSlm on 16.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import CryptoKit


// MARK:  TEXT FIELDS CHECKING

class LoginWorker {
    
    func check3Fields(userName: String?, password: String?, confirmPassword: String?) -> String {
        let textList = TextList.shared.getloginUI()
        var message = textList.messageSuccess
        //
        
        guard let userName = userName, let password = password, let confirmPassword = confirmPassword  else {
            message = textList.messageFieldsEmpty
            return message
        }
        if password != confirmPassword {
            message = textList.messagePasswordsDontMatch
        }
        

        
        if userName == "" || password == "" || confirmPassword == "" {
            message = textList.messageFieldsEmpty
        }
        
        for symbol in userName {
            if symbol == " " {
                message = textList.messageUserNameCannotSpace
            }
        }
        
        return message
    }
}

// MARK:  USER DEFAULTS

extension LoginWorker {
    
    func compareUsers(userName: String, passwordHash: String) -> User? {
        
        let users = CoreDataManager.shared.fetchUsers()
        for user in users {
            if user.name == userName && user.passwordHash == passwordHash {
                return user
            }
        }
        return nil
    }
    
    func checkUserInStore(userName: String) -> Bool {
        var success = true
        let users = CoreDataManager.shared.fetchUsers()
        for user in users {
            if user.name == userName  {
                success = false
            }
        }
        return success
    }
    
}



// MARK:  ENCRYPTION

extension LoginWorker {
    func encryptString(string: String) -> String {
        
        let computed = Insecure.MD5.hash(data: string.data(using: .utf8)!)
        return computed.map { String(format: "%02hhx", $0) }.joined()
    }
}

